### ISSUE TITLE
Camera shift used incorrectly

### ISSUE THREAD

**Issue by imjinc2k** [RayMairlot/Animated-Render-Border#20]
Camera shift is being applied incorrectly to the ARB, when using 2.93LTS, causing problems with motion-tracked camera solve scenes.  This is reproduced by setting ARB to track the default cube, and changing the camera shift values of the default camera even slightly.

**Comment by RayMairlot** [comment]
You're right. Something seems to have changed since 2.79 regarding how I need to calculate the border offset.  I'll look into it.

**Comment by RayMairlot** [comment]
I've worked out what the issue is. Previously, I had to calculate how the camera shift values affected the object positions, and therefore the render border, myself, but Blender was updated a while ago (Blender 2.83.0) to fix this, meaning my calculation is now unnecessary. My calculation on top of Blender's is what caused the render border to be incorrect.

I've now included some versioning code to detect which version of Blender is being used and whether the camera shift values should be calculated manually by me or left to Blender to do.

The updated version of the add-on with the bug fix can now be downloaded from the Blender Market.

Thanks for reporting the issue!
