### ISSUE TITLE
Multiple Output Video Files

### ISSUE THREAD

**Issue by amoxocillina** [RayMairlot/Animated-Render-Border#7]
The output video file is a series of video containers (Mp4 or other container no matters , also tried with every kind of codecs or compression type) with a single frame instead a single file containing all the frames: 
10 frames rendered fill the destination folder with a sequence of video files like :
testvideo001-01.mov
testvideo001-02.mov
testvideo001-03.mov
testvideo001-04.mov
... and so on ... 

tracked object is correctly follower by the border as expected, and the graphic content of the single frames are correctly rendered, however in a useless bunch of videos 1 frame each

system : Linux Mint 18.3 
blender: 2.79b
plugin version: 2.1

**Comment by RayMairlot** [comment]
Hi,

Thanks for reporting this bug. I'm really surprised that neither myself nor anyone who uses the add-on hasn't found this bug before, because it's a pretty obvious one. I think one of the reasons may be that most people will render out image sequences and later compile them into a video file instead of rendering into video directly (as it allows cancelling a render without losing all rendered data), however, it's perfectly reasonable to expect the add-on to respect the format choice correctly.

The issue here is that to get the border to update correctly, renders are done as individual 1 frame renders (which is why the add-on needs its own 'render' button), even when rendering an animation, so that the render border can be updated in between each frame (which is why you are seeing one frame videos). Obviously this doesn't work for videos where it has to be done as one big render.

Unfortunately, even though I can technically change the render border values inbetween frames when doing a render to a video format, the border doesn't actually update - only the size of the border at the start of the render is taken into account. This is likely a limitation of the render border implementation in blender as it was never really intended for the purpose this add-on is using it for.

So, from what I have seen in my tests, the only real course of action is to prevent rendering to a video format and make this clear to the user by presenting error messages in the UI. Not ideal, but it's probably the best solution (the other solution would involve the add-on opening a blank blender file, importing the rendered images to the VSE and then re-rendering to the correct video format, which is quite long-winded).

Thanks for the report. I will hopefully implement the new error messages soon and close this report.

Ray.
